"""empty message

Revision ID: 297c537a4410
Revises: 5dccf23e8d44
Create Date: 2022-05-03 19:39:47.473977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297c537a4410'
down_revision = '5dccf23e8d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
