"""changing password_hash nullable value

Revision ID: 417651c9ee55
Revises: 2d524f80c691
Create Date: 2022-05-04 15:18:40.995994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417651c9ee55'
down_revision = '2d524f80c691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    # ### end Alembic commands ###
