"""empty message

Revision ID: 5dccf23e8d44
Revises: 2d524f80c691
Create Date: 2022-05-03 19:32:38.036998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5dccf23e8d44'
down_revision = '2d524f80c691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'task_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'task_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
