"""Partner rows for app logic updated

Revision ID: 677b76e5c2bf
Revises: 
Create Date: 2022-05-06 09:26:25.129843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '677b76e5c2bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('password_hash', sa.String(length=511), nullable=True))
    op.add_column('partners', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('partners', sa.Column('role', sa.String(), nullable=True))
    op.add_column('products', sa.Column('partner_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.alter_column('products', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'task_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('products_id_partner_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'partners', ['partner_id'], ['id'])
    op.drop_column('products', 'id_partner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id_partner', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_id_partner_fkey', 'products', 'partners', ['id_partner'], ['id'])
    op.alter_column('products', 'task_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('products', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('products', 'partner_id')
    op.drop_column('partners', 'role')
    op.drop_column('partners', 'api_key')
    op.drop_column('partners', 'password_hash')
    # ### end Alembic commands ###
